### ISSUE TITLE
Pretraining on resting-state data

### ISSUE THREAD

**Issue by cnwangy** [zjc062/mind-vis#3]
Is it reasonable to pretrain a vision decoder from rest-state data when subjects viewing only a cross? What if we pretrain on task data with more vision activities?

**Comment by zjc062** [comment]
Hi thank you for your interest in our project! 

The pre-training stage is for the encoder to learn the features in the visual cortex and we think the sample size and subject number are more important here. Thus we chose to use resting-state data mainly because of the amount of data in the HCP dataset (more subjects have rsfMRI than task fMRI). 

In our next step, we also consider using more diverse data (combining rsfMRI and task-evoked fMRI from multiple datasets) for pretraining. But the impact of doing so is subject to future research.

**Comment by cnwangy** [comment]
Thanks! I just wonder if it is the effects of the pertaining. It seems there's no comparison between pretrained encoder and training from scratch encoder in the paper.

**Comment by zjc062** [comment]
Hi, thanks for the follow-up question!

The ablation studies for using trained-from-scratch encoders are in Table 1 — Model 1&2. We performed experiments on the same encoder size (Model 1) and a smaller encoder (to avoid overfitting; Model 2). And the results are significantly worse than using a pre-trained encoder.
